name: Step CI Action
description: Run Step CI workflows
icon: check-circle
color: white
inputs:
  path:
    description: 'Workflow Path'
    required: true
    default: '.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
