name: Step CI Action
author: Step CI
description: Run Step CI workflows
branding:
  icon: check-circle
  color: white
inputs:
  path:
    description: 'Workflow Path'
    required: true
    default: '.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
